// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbjmiaolfojlwkgbxlol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiam1pYW9sZm9qbHdrZ2J4bG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzkxNTQsImV4cCI6MjA1NzYxNTE1NH0.Bg37-UEVEeWbN30bDxHx2Dje7tVC5p2m6JdXpNAVclI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);